apiVersion: v1
kind: Service 
metadata:
  name: frontend-pyapp-loadbalancer-service
  labels:
    app: frontend-pyapp
    tier: frontend  
spec:
  type: LoadBalancer # ClusterIp, # NodePort
  selector:
    app: frontend-pyapp
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 8080 # Container Port